# Generated by Django 6.0.7 on 2026-07-20 11:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Yangilik nomi')),
                ('game_name', models.CharField(blank=True, max_length=150, null=True, verbose_name="O'yin nomi")),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='Rasm')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('expected_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Kutilayotgan narx ($)')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='Chiqish sanasi')),
                ('is_published', models.BooleanField(default=True, verbose_name='Chop etilganmi')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Qo'shilgan vaqti")),
            ],
            options={
                'verbose_name': 'Yangilik',
                'verbose_name_plural': 'Yangiliklar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=200, verbose_name="O'yin nomi")),
                ('category', models.CharField(max_length=100, verbose_name='Kategoriya')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('rasmmi', models.ImageField(upload_to='portfolio/', verbose_name='Rasm')),
                ('texnoligiya', models.CharField(max_length=300, verbose_name='Texnologiyalar (vergul bilan)')),
                ('narxi', models.DecimalField(decimal_places=2, default=29.99, max_digits=8, verbose_name='Narx ($)')),
            ],
            options={
                'verbose_name': 'Portfolio Loyihasi',
                'verbose_name_plural': 'Portfolio Loyihalari',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('proce', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.product')),
            ],
        ),
    ]
