# Generated by Django 6.0.7 on 2026-07-21 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='is_published',
        ),
        migrations.AddField(
            model_name='news',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan vaqti"),
        ),
        migrations.AlterField(
            model_name='news',
            name='expected_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Kutilayotgan narx ($)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='game_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name="O'yin nomi"),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='portfolioproject',
            name='narxi',
            field=models.IntegerField(verbose_name='Narx ($)'),
        ),
    ]
