# Generated by Django 6.0.7 on 2026-07-22 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_news_is_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='expected_price',
        ),
        migrations.RemoveField(
            model_name='portfolioproject',
            name='narxi',
        ),
    ]
