# Generated by Django 6.0.7 on 2026-07-22 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_news_expected_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(verbose_name='oyin nomi')),
                ('rasmi', models.ImageField(upload_to='', verbose_name='rasmi')),
                ('categoriya', models.CharField(verbose_name='kategoriya')),
            ],
            options={
                'verbose_name': "Trending O'yin",
                'verbose_name_plural': "Trending O'yinlar",
            },
        ),
    ]
