# Generated by Django 6.0.7 on 2026-07-22 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_trending'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trending',
            options={'ordering': ['-id'], 'verbose_name': "Trending O'yin", 'verbose_name_plural': "Trending O'yinlar"},
        ),
    ]
